<Button>
    font_size:64
    background_normal: ''
    background_color: (140/255,140/255,140/255,1)

<MyLayout>
    display: display
    canvas.before:
        Color:    
            rgba: (50/255, 50/255, 50/255, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        padding: 100
        spacing: 50

        Label:
            id:display
            multiline:False
            text_size: self.size
            padding:10
            halign: 'right'
            valign: 'middle'
            font_size: 128
            font_name: 'digital-7.ttf'
            size_hint: (1, None)
            height: 200
            background_color: (200/255, 200/255, 200/255, 1)
            canvas.before:
                Color: 
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size

        GridLayout:
            cols: 1
            spacing: (50, 50)

            BoxLayout:
                orientation: 'horizontal'
                spacing: 50

                Button:
                    id: ce_button
                    text: 'CE'
                    on_press: root.clear_entry()

                Button:
                    id: c_button
                    text: 'C'
                    on_press: root.clear_everything()

                Button:
                    id: backspace_button
                    text: '<-'
                    on_press: root.backspace()

                Button:
                    id: plus_button
                    text: '+'
                    background_color: (60/255, 160/255, 190/255, 1)
                    on_press: root.press('+')

            BoxLayout:
                orientation: 'horizontal'
                spacing: 50

                Button:
                    id: num_1
                    text: '1'
                    on_press: root.press('1')
                    

                Button:
                    id: num_2
                    text: '2'
                    on_press: root.press('2')

                Button:
                    id: num_3
                    text: '3'
                    on_press: root.press('3')

                Button:
                    id: minus_button
                    text: '-'
                    background_color: (60/255, 160/255, 190/255, 1)
                    on_press: root.press('-')

            BoxLayout:
                orientation: 'horizontal'
                spacing: 50

                Button:
                    id: num_4
                    text: '4'
                    on_press: root.press('4')

                Button:
                    id: num_5
                    text: '5'
                    on_press: root.press('5')

                Button:
                    id: num_6
                    text: '6'
                    on_press: root.press('6')

                Button:
                    id: times_button
                    text: '×'
                    background_color: (60/255, 160/255, 190/255, 1)
                    on_press: root.press('*')

            BoxLayout:
                orientation: 'horizontal'
                spacing: 50

                Button:
                    id: num_7
                    text: '7'
                    on_press: root.press('7')

                Button:
                    id: num_8
                    text: '8'
                    on_press: root.press('8')

                Button:
                    id: num_9
                    text: '9'
                    on_press: root.press('9')

                Button:
                    id: divide_button
                    text: '÷'
                    background_color: (60/255, 160/255, 190/255, 1)
                    on_press: root.press('/')

            BoxLayout:
                orientation: 'horizontal'
                spacing: 50

                BoxLayout:
                    orientation:'horizontal'
                    spacing: 50

                    Button:
                        id: decimal_button
                        text: '.'
                        on_press: root.press('.')

                    Button:
                        id: num_0
                        text: '0'
                        on_press: root.press('0')
                        
                BoxLayout:
                    orientation:'horizontal'

                    Button:
                        id: equals_button
                        text: '='
                        background_color: (102/255, 209/255, 117/255, 1)
                        on_press: root.calculate()
                        size_hint: (2,1)
                        

